POST http://localhost:3010/email
Content-Type: application/json

{
  "name": "WK Wong",
  "email": "test@mail.com",
  "template": "transaction"
}

### Dev environment

POST https://owjyvo9odh.execute-api.ap-southeast-1.amazonaws.com/email
Content-Type: application/json

{
  "name": "WK Wong",
  "email": "test@mail.com",
  "template": "verification"
}
