on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - name: Install packages
        run: yarn install --frozen-lockfile
      - name: Lint and Test
        run: |
          yarn --cwd services/messaging run lint
          yarn --cwd services/messaging run test
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Build and Deploy
        run: yarn --cwd services/messaging run deploy --stage prod
